name: "Install dependencies"
description: "Composite action to install dependencies"
runs:
  using: composite
  steps:
    - name: Print step name
      run: echo "Installing dependencies has started.."
      shell: bash
    - name: Install Node.js and pm2
      run: |
        curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh
        sudo -E bash nodesource_setup.sh
        sudo apt-get install -y nodejs
        sudo npm install -g pm2
      shell: bash
    - uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
    - name: Install dependencies
      working-directory: python-greetings
      run: pip install -r requirements.txt
      shell: bash