name: "Install dependencies"
description: "Composite action to install dependencies"
runs:
  using: composite
  steps:
    - name: Print step name
      run: echo "Installing dependencies has started.."
      shell: bash
    - uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
    - name: Install dependencies
      working-directory: python-greetings
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
      shell: bash