name: Python Greetings Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: "dev"
          port: "7001"
  tests-on-dev:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: "dev"
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: "staging"
          port: "7002"
  tests-on-staging:
    runs-on: ubuntu-latest
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: "staging"
  deploy-to-preprod:
    runs-on: ubuntu-latest
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: "preprod"
          port: "7003"
  tests-on-preprod:
    runs-on: ubuntu-latest
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: "preprod"
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: "prod"
          port: "7004"
  tests-on-prod:
    runs-on: ubuntu-latest
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: "prod"